DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID      BIGINT       NOT NULL COMMENT '사용자ID',
    NAME         VARCHAR(255) NOT NULL COMMENT '주문명',
    STATUS       VARCHAR(30) NULL COMMENT '주문상태',
    ORDERED_TIME TIMESTAMP    NOT NULL COMMENT '주문시간'
);

DROP TABLE IF EXISTS ORDER_LINE_ITEM;
CREATE TABLE ORDER_LINE_ITEM
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID      BIGINT NULL                       COMMENT '주문 ID',
    PRODUCT_ID    BIGINT         NOT NULL COMMENT '상품ID',
    PRODUCT_NAME  VARCHAR(255)   NOT NULL COMMENT '상품명',
    PRODUCT_PRICE DECIMAL(19, 2) NOT NULL COMMENT '상품가격',
    COUNT         INT            NOT NULL COMMENT '갯수'
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
(
    ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME  VARCHAR(255)   NOT NULL COMMENT '상품명',
    PRICE DECIMAL(19, 2) NOT NULL COMMENT '상품가격',
    STOCK INT            NOT NULL COMMENT '재고수량'
);
